#!/usr/bin/env bash

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
CONFIG_DIR="$XDG_CONFIG_HOME/ags"
CACHE_DIR="$XDG_CACHE_HOME/ags"

CUSTOM_DIR="$XDG_CONFIG_HOME/hypr/custom"
RESTORE_SCRIPT_DIR="$CUSTOM_DIR/scripts"
RESTORE_SCRIPT="$RESTORE_SCRIPT_DIR/__restore_video_wallpaper.sh"

VIDEO_OPTS="no-audio loop hwdec=auto scale=bilinear interpolation=no video-sync=display-resample panscan=1.0 video-scale-x=1.0 video-scale-y=1.0 video-align-x=0.5 video-align-y=0.5"

mkdir -p "$RESTORE_SCRIPT_DIR"

is_video() {
	local extension="${1##*.}"
	[[ "$extension" == "mp4" || "$extension" == "mkv" || "$extension" == "webm" ]] && return 0 || return 1
}

kill_existing_mpvpaper() {
	# Abort all mpvpapers' instance
	pkill -f -9 mpvpaper || true
}

create_restore_script() {
	local video_path=$1

	cat > "$RESTORE_SCRIPT.tmp" << EOF
#!/bin/bash
# Generated by switchwall.sh - Don't modify it by yourself.
# Time: $(date)

pkill -f -9 mpvpaper

for monitor in \$(hyprctl monitors -j | jq -r '.[] | .name'); do
	mpvpaper -o "$VIDEO_OPTS" "\$monitor" "$video_path" &
	sleep 0.1
done
EOF

	mv "$RESTORE_SCRIPT.tmp" "$RESTORE_SCRIPT"
	chmod +x "$RESTORE_SCRIPT"
}

remove_restore() {
	cat > "$RESTORE_SCRIPT.tmp" << EOF
#!/bin/bash
# The content of this script will be generated by switchwall.sh - Don't modify it by yourself.	
EOF

	mv "$RESTORE_SCRIPT.tmp" "$RESTORE_SCRIPT"
}

switch() {
	local monitor=$1
	local imgpath=$2
	read scale screenx screeny screensizey < <(hyprctl monitors -j | jq --arg mon "$monitor" '.[] | select(.name==$mon) | .scale, .x, .y, .height' | xargs)
	cursorposx=$(hyprctl cursorpos -j | jq '.x' 2>/dev/null) || cursorposx=960
	cursorposx=$(bc <<< "scale=0; ($cursorposx - $screenx) * $scale / 1")
	cursorposy=$(hyprctl cursorpos -j | jq '.y' 2>/dev/null) || cursorposy=540
	cursorposy=$(bc <<< "scale=0; ($cursorposy - $screeny) * $scale / 1")
	cursorposy_inverted=$((screensizey - cursorposy))

	if [ "$imgpath" == '' ]; then
		echo "Aborted for monitor $monitor"
		return 1
	fi

	swww img "$imgpath" --outputs "$monitor" \
		--transition-step 100 --transition-fps 120 \
		--transition-type grow --transition-angle 30 --transition-duration 1 \
		--transition-pos "$cursorposx, $cursorposy_inverted"
}

# Get list of monitors
readarray -t monitors < <(hyprctl monitors -j | jq -r '.[].name')
first_monitor_wallpaper=""

cd "$(xdg-user-dir PICTURES)" || exit 1

# Add floating rule for yad dialog
hyprctl keyword windowrule "float,^(yad)$" >/dev/null

# Handle each monitor
for monitor in "${monitors[@]}"; do
	echo "Select wallpaper for monitor: $monitor"
	imgpath=$(yad --width 1200 --height 800 --file --add-preview --large-preview --title="Choose wallpaper for $monitor")
	
	# Store first monitor's wallpaper for color generation
	if [ "$monitor" = "${monitors[0]}" ]; then
		first_monitor_wallpaper="$imgpath"
	fi
	
	switch "$monitor" "$imgpath"
done

# Remove the floating rule after we're done
hyprctl keyword windowrule "unset,^(yad)$" >/dev/null

# Generate colors for ags using the first monitor's wallpaper
"$CONFIG_DIR"/scripts/color_generation/colorgen.sh "${first_monitor_wallpaper}" --apply --smart
