#!/usr/bin/env bash

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
CONFIG_DIR="$XDG_CONFIG_HOME/ags"
CACHE_DIR="$XDG_CACHE_HOME/ags"

# Video wallpaper related (inspired by GitHub script)
THUMBNAIL_DIR="/tmp/mpvpaper_thumbnails"
CUSTOM_DIR="$XDG_CONFIG_HOME/hypr/custom" # Assuming your hypr config might be here
RESTORE_SCRIPT_DIR="$CUSTOM_DIR/scripts"
RESTORE_SCRIPT="$RESTORE_SCRIPT_DIR/__restore_video_wallpaper.sh"
VIDEO_OPTS="no-audio loop hwdec=auto scale=bilinear interpolation=no video-sync=display-resample panscan=1.0 video-scale-x=1.0 video-scale-y=1.0 video-align-x=0.5 video-align-y=0.5"

# Create necessary directories
mkdir -p "$THUMBNAIL_DIR"
mkdir -p "$RESTORE_SCRIPT_DIR"

# --- Helper Functions ---
is_video() {
    local filename="$1"
    local extension="${filename##*.}"
    extension="${extension,,}" # to lowercase
    [[ "$extension" == "mp4" || "$extension" == "mkv" || "$extension" == "webm" ]] && return 0 || return 1
}

kill_existing_mpvpaper() {
    echo "Stopping existing mpvpaper instances..."
    pkill -f -9 mpvpaper || true
}

create_restore_script() {
    local video_path="$1"
    echo "Creating restore script for video: $video_path"
    # Create restore script for all monitors with the SAME video
    cat > "$RESTORE_SCRIPT.tmp" << EOF
#!/bin/bash
# Generated by wallpaper switcher - Don't modify it by yourself.
# Time: $(date)

echo "Restoring video wallpaper: $video_path"
pkill -f -9 mpvpaper || true # Kill any existing before starting

# Give a small delay for system to settle if run at startup
# sleep 3 

for monitor in \$(hyprctl monitors -j | jq -r '.[] | .name'); do
    echo "Applying to monitor: \$monitor"
    mpvpaper -o "$VIDEO_OPTS" "\$monitor" "$video_path" &
    sleep 0.2 # Stagger starts slightly, ensure processes launch
done
EOF
    mv "$RESTORE_SCRIPT.tmp" "$RESTORE_SCRIPT"
    chmod +x "$RESTORE_SCRIPT"
}

remove_restore() {
    echo "Removing video wallpaper restore script."
    cat > "$RESTORE_SCRIPT.tmp" << EOF
#!/bin/bash
# No video wallpaper set. This script is intentionally blank.
# Generated by wallpaper switcher.
# Time: $(date)
EOF
    mv "$RESTORE_SCRIPT.tmp" "$RESTORE_SCRIPT"
    # No need to chmod +x a blank script, but doesn't hurt
    chmod +x "$RESTORE_SCRIPT"
}

# Function to apply a static image to a specific monitor
apply_static_wallpaper() {
    local monitor="$1"
    local imgpath="$2"

    if [ -z "$imgpath" ]; then
        echo "No image path provided for monitor $monitor. Skipping."
        return 1
    fi
    if [ ! -f "$imgpath" ]; then
        echo "Image path does not exist for monitor $monitor: $imgpath. Skipping."
        return 1
    fi

    echo "Applying static wallpaper '$imgpath' to monitor '$monitor'"
    # Ensure swww daemon is running
    if ! pgrep -f swww-daemon > /dev/null; then
        echo "swww-daemon not running. Attempting to start it..."
        (swww init &) # Start in background if not already running
        sleep 1       # Give it a moment to initialize
        if ! pgrep -f swww-daemon > /dev/null; then
            echo "Error: Failed to start swww-daemon. Cannot set static wallpaper."
            return 1
        fi
    fi

    swww img "$imgpath" --outputs "$monitor" \
        --transition-step 100 --transition-fps 120 \
        --transition-type grow --transition-angle 30 --transition-duration 1
    # Add other swww options if needed from your original switch()
}

# --- --noswitch Handling ---
if [ "$1" == "--noswitch" ]; then
    echo "Running --noswitch: Applying colorgen to current wallpaper..."
    current_wallpaper_path=""
    source_for_colorgen=""

    if pgrep -f mpvpaper > /dev/null; then
        # Attempt to get the path from mpvpaper's command line
        # This assumes the path is the last argument not starting with '-' and contains a video extension.
        current_wallpaper_path=$(ps -eo cmd | grep '[m]pvpaper' | grep -E '\.mp4|\.mkv|\.webm' | awk '{print $NF}' | head -n 1)

        if [ -n "$current_wallpaper_path" ] && [ -f "$current_wallpaper_path" ]; then
            echo "Detected video wallpaper: $current_wallpaper_path"
            thumbnail_path="$THUMBNAIL_DIR/$(basename "$current_wallpaper_path").jpg" # Consistent thumbnail name
            
            # Ensure thumbnail exists and is up-to-date for colorgen
            if [ ! -f "$thumbnail_path" ] || [ "$current_wallpaper_path" -nt "$thumbnail_path" ]; then
                echo "Generating thumbnail for $current_wallpaper_path..."
                ffmpeg -y -i "$current_wallpaper_path" -vframes 1 "$thumbnail_path" 2>/dev/null
            fi

            if [ -f "$thumbnail_path" ];
                then source_for_colorgen="$thumbnail_path";
                else echo "Error: Cannot create/find thumbnail for video wallpaper at '$thumbnail_path'.";
            fi
        else
            echo "Warning: mpvpaper is running but could not reliably determine the video path for colorgen."
        fi
    elif pgrep -f swww-daemon > /dev/null; then
        current_wallpaper_path=$(swww query | awk -F 'image: ' 'NR==1 {print $2}') # User's original logic for first monitor
        if [ -n "$current_wallpaper_path" ] && [ -f "$current_wallpaper_path" ]; then
            echo "Detected static wallpaper on first monitor: $current_wallpaper_path"
            source_for_colorgen="$current_wallpaper_path"
        else
            echo "Warning: swww-daemon is running but could not determine wallpaper path or file does not exist for colorgen."
        fi
    else
        echo "No known wallpaper manager (mpvpaper or swww-daemon) seems to be active for --noswitch."
    fi

    if [ -n "$source_for_colorgen" ]; then
        echo "Applying color scheme from: $source_for_colorgen"
        "$CONFIG_DIR"/scripts/color_generation/colorgen.sh "$source_for_colorgen" --apply --smart
    else
        echo "Could not determine wallpaper for colorgen in --noswitch mode."
    fi
    exit 0
fi

# --- Main Script Logic ---

# Add floating rule for yad dialog
hyprctl keyword windowrule "float,^(yad)$" >/dev/null 2>&1

# Navigate to pictures directory
cd "$(xdg-user-dir PICTURES)/Wallpapers" || cd "$(xdg-user-dir PICTURES)" || {
    echo "Error: Could not navigate to a suitable Pictures directory."
    hyprctl keyword windowrule "unset,^(yad)$" >/dev/null 2>&1
    exit 1
}

echo "Select the primary wallpaper. If it's a video, it will apply to all monitors."
initial_selection=$(yad --width 1200 --height 800 --file --add-preview --large-preview --title='Choose primary wallpaper (video applies to all)')

if [ -z "$initial_selection" ]; then
    echo "No file selected. Aborted."
    hyprctl keyword windowrule "unset,^(yad)$" >/dev/null 2>&1
    exit 0
fi

if [ ! -f "$initial_selection" ]; then
    echo "Error: Selected file does not exist: $initial_selection"
    hyprctl keyword windowrule "unset,^(yad)$" >/dev/null 2>&1
    exit 1
fi


if is_video "$initial_selection"; then
    echo "Video file selected: $initial_selection. Applying to all monitors."
    VIDEO_WALLPAPER_PATH="$initial_selection"

    missing_deps=()
    if ! command -v mpvpaper &> /dev/null; then missing_deps+=("mpvpaper"); fi
    if ! command -v ffmpeg &> /dev/null; then missing_deps+=("ffmpeg"); fi
    if [ ${#missing_deps[@]} -gt 0 ]; then
        yad --error --text="Missing dependencies: ${missing_deps[*]}.\nPlease install them (e.g., on Arch: yay -S ${missing_deps[*]})" --width=400 --height=100
        hyprctl keyword windowrule "unset,^(yad)$" >/dev/null 2>&1
        exit 1
    fi

    pkill -f swww-daemon || true # Stop swww daemon if running
    kill_existing_mpvpaper

    echo "Starting mpvpaper for all monitors..."
    monitors_list=$(hyprctl monitors -j | jq -r '.[] | .name')
    if [ -z "$monitors_list" ]; then
        echo "Error: No monitors detected by Hyprland."
        hyprctl keyword windowrule "unset,^(yad)$" >/dev/null 2>&1
        exit 1
    fi

    for monitor_name in $monitors_list; do
        echo "Applying video to $monitor_name"
        mpvpaper -o "$VIDEO_OPTS" "$monitor_name" "$VIDEO_WALLPAPER_PATH" &
        sleep 0.1 # Stagger start slightly
    done

    echo "Generating thumbnail for color generation..."
    # Use a consistent thumbnail name for simplicity with --noswitch
    thumbnail_path="$THUMBNAIL_DIR/$(basename "$VIDEO_WALLPAPER_PATH").jpg"
    ffmpeg -y -i "$VIDEO_WALLPAPER_PATH" -vframes 1 "$thumbnail_path" 2>/dev/null

    if [ -f "$thumbnail_path" ]; then
        echo "Applying color scheme from thumbnail: $thumbnail_path"
        "$CONFIG_DIR"/scripts/color_generation/colorgen.sh "$thumbnail_path" --apply --smart
    else
        echo "Error: Cannot create thumbnail for color generation from video."
    fi

    create_restore_script "$VIDEO_WALLPAPER_PATH"
    echo "Video wallpaper setup complete."

else # Selected file is an image
    echo "Image file selected: $initial_selection. Setting up static wallpapers."
    IMAGE_FOR_FIRST_MONITOR="$initial_selection"

    kill_existing_mpvpaper # Stop any video wallpaper
    remove_restore         # Remove video restore script

    readarray -t monitors < <(hyprctl monitors -j | jq -r '.[].name')
    
    if [ ${#monitors[@]} -eq 0 ]; then
        echo "Error: No monitors detected by Hyprland."
        hyprctl keyword windowrule "unset,^(yad)$" >/dev/null 2>&1
        exit 1
    fi

    first_monitor_name="${monitors[0]}"
    apply_static_wallpaper "$first_monitor_name" "$IMAGE_FOR_FIRST_MONITOR"
    wallpaper_for_colorgen="$IMAGE_FOR_FIRST_MONITOR"

    if [ ${#monitors[@]} -gt 1 ]; then
        echo "Proceeding to select wallpapers for other monitors..."
        for i in $(seq 1 $((${#monitors[@]} - 1))); do
            current_monitor_name="${monitors[$i]}"
            imgpath_other=$(yad --width 1200 --height 800 --file --add-preview --large-preview --title="Choose wallpaper for $current_monitor_name")
            
            if [ -n "$imgpath_other" ] && [ -f "$imgpath_other" ]; then
                apply_static_wallpaper "$current_monitor_name" "$imgpath_other"
            elif [ -n "$imgpath_other" ]; then # Path provided but file doesn't exist
                 echo "Warning: Selected file for $current_monitor_name does not exist: $imgpath_other. Skipping."
            else
                echo "No wallpaper selected for $current_monitor_name. It will keep its current wallpaper or be handled by swww's default behavior."
            fi
        done
    fi
    
    if [ -n "$wallpaper_for_colorgen" ] && [ -f "$wallpaper_for_colorgen" ]; then
        echo "Applying color scheme from first monitor's wallpaper: $wallpaper_for_colorgen"
        "$CONFIG_DIR"/scripts/color_generation/colorgen.sh "$wallpaper_for_colorgen" --apply --smart
    else
        echo "Warning: Could not determine wallpaper for color generation for static images."
    fi
    echo "Static wallpaper setup complete."
fi

# Remove the floating rule after we're done
hyprctl keyword windowrule "unset,^(yad)$" >/dev/null 2>&1

exit 0
